"""Auditable practical-method utility comparisons.

The Stage-1 result schema already defines ``delta_wga`` as the change in
worst-group accuracy after verification and retraining relative to the
no-correction model.  This module keeps that *absolute* effect separate from
the paired comparison against the ``loss`` acquisition baseline.

The distinction matters for diagnostic claims: a method can be worse than
Loss while still helping relative to no correction, or it can harm WGA in
absolute terms.  All comparisons are paired by outer corruption seed; budget
is retained as a condition label and is never pooled as an independent sample.
"""
from __future__ import annotations

from dataclasses import dataclass
from math import comb
from typing import Iterable, Sequence

import numpy as np
import pandas as pd


REQUIRED_COLUMNS = {"noise_name", "seed", "method", "budget_fraction", "delta_wga"}
KEY_COLUMNS = ["dataset", "noise_name", "seed", "method", "budget_fraction"]
CONDITION_COLUMNS = ["dataset", "noise_name", "budget_fraction"]


@dataclass(frozen=True)
class AbsoluteUtilityAudit:
    """Tables and integrity metadata generated by :func:`audit_absolute_utility`."""

    absolute_vs_no_correction: pd.DataFrame
    paired_vs_loss: pd.DataFrame
    per_seed_absolute: pd.DataFrame
    per_seed_vs_loss: pd.DataFrame
    coverage: pd.DataFrame
    metadata: dict[str, object]


def _as_numeric(frame: pd.DataFrame, columns: Iterable[str]) -> None:
    for column in columns:
        frame[column] = pd.to_numeric(frame[column], errors="raise")


def prepare_results(frame: pd.DataFrame, dataset: str | None = None) -> pd.DataFrame:
    """Validate and normalize one raw ``results.csv`` frame.

    ``delta_wga`` is required because it is the canonical absolute effect
    relative to no correction.  When ``wga`` and ``baseline_wga`` are present,
    their difference is checked against that canonical value to catch a mixed
    baseline or incorrectly exported result file early.
    """
    missing = REQUIRED_COLUMNS.difference(frame.columns)
    if missing:
        raise ValueError(f"Missing required result columns: {sorted(missing)}")

    result = frame.copy()
    if dataset is not None:
        result["dataset"] = str(dataset)
    elif "dataset" not in result.columns:
        result["dataset"] = "unknown"
    else:
        result["dataset"] = result["dataset"].astype(str)

    _as_numeric(result, ("seed", "budget_fraction", "delta_wga"))
    if not np.isfinite(result["delta_wga"].to_numpy(float)).all():
        raise ValueError("delta_wga contains non-finite values")
    if (result["budget_fraction"] < 0).any():
        raise ValueError("budget_fraction must be non-negative")
    if result["method"].isna().any() or result["noise_name"].isna().any():
        raise ValueError("method and noise_name must not contain missing values")

    # CSV round-tripping may produce harmless binary noise in a budget field.
    result["budget_fraction"] = result["budget_fraction"].round(12)
    duplicate = result.duplicated(KEY_COLUMNS, keep=False)
    if duplicate.any():
        examples = result.loc[duplicate, KEY_COLUMNS].head(5).to_dict("records")
        raise ValueError(f"Duplicate result keys; refusing to pool them: {examples}")

    if {"wga", "baseline_wga"}.issubset(result.columns):
        _as_numeric(result, ("wga", "baseline_wga"))
        expected = result["wga"] - result["baseline_wga"]
        mismatch = ~np.isclose(
            result["delta_wga"].to_numpy(float), expected.to_numpy(float), atol=1e-9, rtol=1e-9
        )
        if mismatch.any():
            examples = result.loc[mismatch, KEY_COLUMNS + ["wga", "baseline_wga", "delta_wga"]]
            raise ValueError(
                "delta_wga does not equal wga - baseline_wga; this would invalidate "
                f"the no-correction comparison. Examples: {examples.head(5).to_dict('records')}"
            )
        result["_absolute_effect_source"] = "verified_wga_minus_baseline_wga"
    else:
        result["_absolute_effect_source"] = "reported_delta_wga"
    return result


def exact_two_sided_sign_test(values: Sequence[float], *, tolerance: float = 0.0) -> float:
    """Return an exact two-sided sign-test p-value, dropping ties.

    This intentionally avoids an optional scipy dependency.  It is descriptive
    evidence alongside the bootstrap interval, not a correction for selecting
    a result from a large experimental matrix.
    """
    array = np.asarray(values, dtype=float)
    positives = int((array > tolerance).sum())
    negatives = int((array < -tolerance).sum())
    n_non_tied = positives + negatives
    if n_non_tied == 0:
        return 1.0
    lower_tail = sum(comb(n_non_tied, index) for index in range(min(positives, negatives) + 1))
    return float(min(1.0, 2.0 * lower_tail / (2**n_non_tied)))


def bootstrap_mean_ci(
    values: Sequence[float], rng: np.random.Generator, n_bootstrap: int
) -> tuple[float, float]:
    """Return a percentile bootstrap CI for a seed-level mean."""
    array = np.asarray(values, dtype=float)
    if not len(array):
        return float("nan"), float("nan")
    if n_bootstrap <= 0:
        raise ValueError("n_bootstrap must be positive")
    indices = rng.integers(0, len(array), size=(n_bootstrap, len(array)))
    means = array[indices].mean(axis=1)
    low, high = np.quantile(means, [0.025, 0.975])
    return float(low), float(high)


def _effect_label(
    ci_low: float,
    ci_high: float,
    *,
    epsilon: float,
    harm_label: str,
    benefit_label: str,
) -> str:
    if ci_high < -epsilon:
        return harm_label
    if ci_low > epsilon:
        return benefit_label
    return "inconclusive"


def _effect_summary(
    values: Sequence[float],
    *,
    rng: np.random.Generator,
    n_bootstrap: int,
    epsilon: float,
    harm_label: str,
    benefit_label: str,
) -> dict[str, float | int | str]:
    array = np.asarray(values, dtype=float)
    ci_low, ci_high = bootstrap_mean_ci(array, rng, n_bootstrap)
    n_harm = int((array < -epsilon).sum())
    n_benefit = int((array > epsilon).sum())
    return {
        "n_paired_seeds": int(len(array)),
        "mean_effect": float(array.mean()),
        "median_effect": float(np.median(array)),
        "std_effect": float(array.std(ddof=1)) if len(array) > 1 else 0.0,
        "bootstrap_ci_low": ci_low,
        "bootstrap_ci_high": ci_high,
        "harmful_seed_count": n_harm,
        "beneficial_seed_count": n_benefit,
        "tie_seed_count": int(len(array) - n_harm - n_benefit),
        "harmful_seed_rate": float(n_harm / len(array)),
        "sign_test_two_sided_p": exact_two_sided_sign_test(array, tolerance=epsilon),
        "evidence": _effect_label(
            ci_low,
            ci_high,
            epsilon=epsilon,
            harm_label=harm_label,
            benefit_label=benefit_label,
        ),
    }


def select_practical_methods(
    results: pd.DataFrame,
    *,
    loss_method: str = "loss",
    no_correction_method: str = "no_correction",
    include_methods: Sequence[str] | None = None,
    exclude_methods: Sequence[str] = (),
) -> list[str]:
    """Select legal/practical methods, conservatively excluding oracle rows."""
    available = sorted(results["method"].astype(str).unique().tolist())
    requested = available if include_methods is None else list(dict.fromkeys(include_methods))
    unknown = sorted(set(requested).difference(available))
    if unknown:
        raise ValueError(f"Requested methods are absent from the results: {unknown}")

    excluded = set(exclude_methods) | {loss_method, no_correction_method}
    practical = [
        method
        for method in requested
        if method not in excluded and "oracle" not in method.lower()
    ]
    if not practical:
        raise ValueError("No practical methods remain after excluding references and oracle methods")
    return sorted(practical)


def _baseline_integrity(results: pd.DataFrame) -> dict[str, int | str]:
    """Summarize whether the no-correction baseline is consistently exported."""
    source = sorted(results["_absolute_effect_source"].unique().tolist())
    metadata: dict[str, int | str] = {
        "absolute_effect_source": ",".join(source),
        "baseline_variation_groups": 0,
    }
    if "baseline_wga" not in results.columns:
        return metadata
    group_columns = ["dataset", "noise_name", "seed"]
    variation = results.groupby(group_columns, sort=True)["baseline_wga"].agg(lambda values: values.max() - values.min())
    metadata["baseline_variation_groups"] = int((variation.abs() > 1e-9).sum())
    return metadata


def audit_absolute_utility(
    results: pd.DataFrame,
    *,
    loss_method: str = "loss",
    no_correction_method: str = "no_correction",
    include_methods: Sequence[str] | None = None,
    exclude_methods: Sequence[str] = (),
    epsilon: float = 0.0,
    n_bootstrap: int = 10_000,
    rng_seed: int = 20260724,
) -> AbsoluteUtilityAudit:
    """Compute absolute effects versus no correction and paired effects versus Loss.

    The input must already be normalized by :func:`prepare_results`.  Keeping
    preparation separate lets callers concatenate multiple dataset files while
    still rejecting duplicate condition/seed/method rows globally.
    """
    if epsilon < 0:
        raise ValueError("epsilon must be non-negative")
    if n_bootstrap <= 0:
        raise ValueError("n_bootstrap must be positive")

    practical_methods = select_practical_methods(
        results,
        loss_method=loss_method,
        no_correction_method=no_correction_method,
        include_methods=include_methods,
        exclude_methods=exclude_methods,
    )
    practical = results[results["method"].isin(practical_methods)].copy()
    rng = np.random.default_rng(rng_seed)

    absolute_rows: list[dict[str, object]] = []
    absolute_seed_rows: list[dict[str, object]] = []
    for condition, group in practical.groupby(CONDITION_COLUMNS + ["method"], sort=True):
        values = group["delta_wga"].to_numpy(float)
        row = dict(zip(CONDITION_COLUMNS + ["method"], condition, strict=True))
        row.update(
            {
                "comparator": no_correction_method,
                "effect_definition": "delta_wga = WGA(method) - WGA(no_correction)",
                **_effect_summary(
                    values,
                    rng=rng,
                    n_bootstrap=n_bootstrap,
                    epsilon=epsilon,
                    harm_label="absolute_harm_vs_no_correction",
                    benefit_label="absolute_benefit_vs_no_correction",
                ),
                "mean_method_wga": float(group["wga"].mean()) if "wga" in group else float("nan"),
                "mean_no_correction_wga": (
                    float(group["baseline_wga"].mean()) if "baseline_wga" in group else float("nan")
                ),
            }
        )
        absolute_rows.append(row)
        for _, record in group.iterrows():
            absolute_seed_rows.append(
                {
                    **{key: record[key] for key in CONDITION_COLUMNS + ["seed", "method"]},
                    "comparator": no_correction_method,
                    "absolute_delta_wga": float(record["delta_wga"]),
                    "method_wga": float(record["wga"]) if "wga" in record else float("nan"),
                    "no_correction_wga": (
                        float(record["baseline_wga"]) if "baseline_wga" in record else float("nan")
                    ),
                    "absolute_effect_source": record["_absolute_effect_source"],
                }
            )

    paired_rows: list[dict[str, object]] = []
    paired_seed_rows: list[dict[str, object]] = []
    coverage_rows: list[dict[str, object]] = []
    for condition, condition_frame in results.groupby(CONDITION_COLUMNS, sort=True):
        loss = condition_frame[condition_frame["method"] == loss_method][["seed", "delta_wga"]].rename(
            columns={"delta_wga": "loss_delta_wga"}
        )
        for method in practical_methods:
            candidate = condition_frame[condition_frame["method"] == method][["seed", "delta_wga"]].rename(
                columns={"delta_wga": "method_delta_wga"}
            )
            joined = candidate.merge(loss, on="seed", how="inner", validate="one_to_one")
            coverage = dict(zip(CONDITION_COLUMNS, condition, strict=True))
            coverage.update(
                {
                    "method": method,
                    "loss_method": loss_method,
                    "candidate_seed_count": int(len(candidate)),
                    "loss_seed_count": int(len(loss)),
                    "paired_seed_count": int(len(joined)),
                    "unpaired_candidate_seed_count": int(len(candidate) - len(joined)),
                    "unpaired_loss_seed_count": int(len(loss) - len(joined)),
                    "loss_available": bool(len(loss)),
                }
            )
            coverage_rows.append(coverage)
            if joined.empty:
                continue
            values = (joined["method_delta_wga"] - joined["loss_delta_wga"]).to_numpy(float)
            row = dict(zip(CONDITION_COLUMNS, condition, strict=True))
            row.update(
                {
                    "method": method,
                    "comparator": loss_method,
                    "effect_definition": "delta_wga(method) - delta_wga(loss)",
                    **_effect_summary(
                        values,
                        rng=rng,
                        n_bootstrap=n_bootstrap,
                        epsilon=epsilon,
                        harm_label="relative_harm_vs_loss",
                        benefit_label="relative_benefit_vs_loss",
                    ),
                    "mean_method_delta_wga": float(joined["method_delta_wga"].mean()),
                    "mean_loss_delta_wga": float(joined["loss_delta_wga"].mean()),
                }
            )
            paired_rows.append(row)
            for _, record in joined.iterrows():
                paired_seed_rows.append(
                    {
                        **dict(zip(CONDITION_COLUMNS, condition, strict=True)),
                        "seed": int(record["seed"]),
                        "method": method,
                        "comparator": loss_method,
                        "method_delta_wga": float(record["method_delta_wga"]),
                        "loss_delta_wga": float(record["loss_delta_wga"]),
                        "paired_delta_wga_vs_loss": float(
                            record["method_delta_wga"] - record["loss_delta_wga"]
                        ),
                    }
                )

    metadata: dict[str, object] = {
        "n_input_rows": int(len(results)),
        "datasets": sorted(results["dataset"].astype(str).unique().tolist()),
        "practical_methods": practical_methods,
        "loss_method": loss_method,
        "no_correction_method": no_correction_method,
        "effect_epsilon": epsilon,
        "bootstrap_replicates": n_bootstrap,
        "rng_seed": rng_seed,
        **_baseline_integrity(results),
    }
    return AbsoluteUtilityAudit(
        absolute_vs_no_correction=pd.DataFrame(absolute_rows),
        paired_vs_loss=pd.DataFrame(paired_rows),
        per_seed_absolute=pd.DataFrame(absolute_seed_rows),
        per_seed_vs_loss=pd.DataFrame(paired_seed_rows),
        coverage=pd.DataFrame(coverage_rows),
        metadata=metadata,
    )
